# Site wide configuration

title                   : "Demographic Digest"
description             : "Демографический Дайджест – регулярная рубрика журнала Демоскоп Weekly, в которой приводятся краткие обзоры демографических статей, публикуемых в ведущих зарубежных журналах."
logo                    : logo-120x120.png
teaser                  : # 400x250 px default teaser image used in image archive grid
locale                  : en
url                     : https://ikashnitsky.github.io/dem-digest
feed:
  path                  : atom.xml
encoding: UTF-8

# Jekyll configuration

sass:
  sass_dir              : _sass
  style                 : compressed
permalink               : /:categories/:year/:title/
markdown                : kramdown
highlighter             : rouge
kramdown:
  toc_levels            : 1..2
  mathjax               : true
  input                 : GFM
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name                  : "Ilya Kashnitsky"
  email                 : "ilya.kashnitsky@gmail.com"
  twitter               : "ikashnitsky"
  github                : "ikashnitsky"
  facebook              : "ikashnitsky"
  bio                   : "Ilya Kashnitsky is a PhD candidate in demography at University of Groningen and Netherlands Interdisciplinary Demographic Institute."
  avatar                : bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname      :

include: ["_pages", ".htaccess"]
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
